post = {
    "wsgi.errors": "<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f3d7caa0a90>",
    "wsgi.version": (1, 0),
    "wsgi.multithread": False,
    "wsgi.multiprocess": False,
    "wsgi.run_once": False,
    "wsgi.file_wrapper": "<class 'gunicorn.http.wsgi.FileWrapper'>",
    "wsgi.input_terminated": True,
    "SERVER_SOFTWARE": "gunicorn/20.0.4",
    "wsgi.input": "<gunicorn.http.body.Body object at 0x7f3d7caa06d0>",
    "gunicorn.socket": "<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 64542)>",
    "REQUEST_METHOD": "POST",
    "QUERY_STRING": "",
    "RAW_URI": "/",
    "SERVER_PROTOCOL": "HTTP/1.1",
    "HTTP_HOST": "localhost:8000",
    "HTTP_CONNECTION": "keep-alive",
    "CONTENT_LENGTH": "26",
    "HTTP_CACHE_CONTROL": "max-age=0",
    "HTTP_SEC_CH_UA": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
    "HTTP_SEC_CH_UA_MOBILE": "?0",
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
    "HTTP_ORIGIN": "http://localhost:8000",
    "CONTENT_TYPE": "application/x-www-form-urlencoded",
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "HTTP_SEC_FETCH_SITE": "same-origin",
    "HTTP_SEC_FETCH_MODE": "navigate",
    "HTTP_SEC_FETCH_USER": "?1",
    "HTTP_SEC_FETCH_DEST": "document",
    "HTTP_REFERER": "http://localhost:8000/",
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, br",
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.9",
    "HTTP_COOKIE": "Webstorm-be5713b7=91394afa-6ed4-4471-8c6e-8ce6110ef379",
    "wsgi.url_scheme": "http",
    "REMOTE_ADDR": "127.0.0.1",
    "REMOTE_PORT": "64542",
    "SERVER_NAME": "127.0.0.1",
    "SERVER_PORT": "8000",
    "PATH_INFO": "/",
    "SCRIPT_NAME": "",
}
get = {
    "wsgi.errors": "<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f3d7caa09d0>",
    "wsgi.version": (1, 0),
    "wsgi.multithread": False,
    "wsgi.multiprocess": False,
    "wsgi.run_once": False,
    "wsgi.file_wrapper": "<class 'gunicorn.http.wsgi.FileWrapper'>",
    "wsgi.input_terminated": True,
    "SERVER_SOFTWARE": "gunicorn/20.0.4",
    "wsgi.input": "<gunicorn.http.body.Body object at 0x7f3d7caa0a30>",
    "gunicorn.socket": "<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 64543)>",
    "REQUEST_METHOD": "GET",
    "QUERY_STRING": "",
    "RAW_URI": "/static/css/computer.css",
    "SERVER_PROTOCOL": "HTTP/1.1",
    "HTTP_HOST": "localhost:8000",
    "HTTP_CONNECTION": "keep-alive",
    "HTTP_SEC_CH_UA": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
    "HTTP_SEC_CH_UA_MOBILE": "?0",
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "HTTP_ACCEPT": "text/css,*/*;q=0.1",
    "HTTP_SEC_FETCH_SITE": "same-origin",
    "HTTP_SEC_FETCH_MODE": "no-cors",
    "HTTP_SEC_FETCH_DEST": "style",
    "HTTP_REFERER": "http://localhost:8000/",
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, br",
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.9",
    "HTTP_COOKIE": "Webstorm-be5713b7=91394afa-6ed4-4471-8c6e-8ce6110ef379",
    "wsgi.url_scheme": "http",
    "REMOTE_ADDR": "127.0.0.1",
    "REMOTE_PORT": "64543",
    "SERVER_NAME": "127.0.0.1",
    "SERVER_PORT": "8000",
    "PATH_INFO": "/static/css/computer.css",
    "SCRIPT_NAME": "",
}
